name = "DirWalker"
uuid = "1a0cd672-5218-4b50-b7a8-cc4b8a5d9145"
authors = ["R. Scott McIntire"]
version = "0.1.4"

[deps]

[compat]
julia = "1.10"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
doc = ["Documenter", "DocumenterTools"]
test = ["Test"]
